### ISSUE TITLE
bro bro ek number ko baar baar bomb q nhi kr skte bro 

### ISSUE THREAD

**Issue by foolish99** [samay825/Sms-Bomb#10]
mjhe bro ek hi number pe bomber lgana h baar baar pr tmhre me set kiya hua hai ek baar hi kr skte hai ek numbr to ye iaaue h mra or bro paid version chahiye mjhe bro 
already txtd u in Instagram (vampier_ritik) isi me kiya hu txt tmko 

mra username subhrat_jain hai 

ho skega to bro isi m fix kr do na like 1 number ko hi baar baar bomb kar sake or tmhra bomber ek numbr hai mtlb pls bro kr do yr

**Comment by samay825** [comment]
ok bro mei msg kartah ho apko !
