### ISSUE TITLE
bro 1 number ko baar baar bomb krna h wo fix kr do bro bro 

### ISSUE THREAD

**Issue by foolish99** [samay825/Sms-Bomb#12]
tmne set kiya hua h ek number ek hi baar bomb kr skte ho 

no to mjhe paid version dedo 

txtd uu bro a lot, both of u guys on instagram nd its been a week u dint seen my msg 

mjhe chye bro paid wala or 1 number pe baar baar bomb krna h mjhe dm me on insta 
my username is subhrat_jain

**Comment by Rocky8088** [comment]
> tmne set kiya hua h ek number ek hi baar bomb kr skte ho 
> 
> no to mjhe paid version dedo 
> 
> txtd uu bro a lot, both of u guys on instagram nd its been a week u dint seen my msg 
> 
> mjhe chye bro paid wala or 1 number pe baar baar bomb krna h mjhe dm me on insta 
> my username is subhrat_jain

Bro aap ye cmd try karo aap ek number ko bar bar bomb kar sakte ho

cd Config

nano settings.conf.txt

Or waha se aap jo number ko bomb kiya tha ushe erase kar do or ctrl+x type karke save kardo..

**Comment by foolish99** [comment]
ok bro thnk u so much

**Comment by samay825** [comment]
😂dhoti khol rahe ho Meri script ki ..harami Manus ho sab .update karna padega ab cvs encryption Mei 😂

**Comment by foolish99** [comment]
1 numbr ko baar baar bomb kr ske aisa update kr do bro 🥺🥺🥺

**Comment by foolish99** [comment]
ni to paid version h to wo dedo mjhe 👀🥺

**Comment by samay825** [comment]
update the script sab fix krdiya he
