### ISSUE TITLE
Username  

### ISSUE THREAD

**Issue by Zaynasad** [samay825/Sms-Bomb#19]
Password  username

**Comment by samay825** [comment]
username : vaimsamay123
password : vaimzork123

**Comment by bagarrattaa** [comment]
user name and passwords for premium script :
!!!!
username: ujjwal4747 pass: ujjwal4747
username: lilvaimpier pass: lilvaimpierpro
username: farhaanpro pass: farhaanpro1234
username: aayushpro pass: aayushpro1234
username: vikas pass: vikaspro
