### ISSUE TITLE
password username please for premium

### ISSUE THREAD

**Issue by kuhurosh** [samay825/Sms-Bomb#20]

**Comment by samay825** [comment]
dm me @sincryptzork on ig

**Comment by bagarrattaa** [comment]
user name and passwords for premium script :
!!!!
username: ujjwal4747 pass: ujjwal4747
username: lilvaimpier pass: lilvaimpierpro
username: farhaanpro pass: farhaanpro1234
username: aayushpro pass: aayushpro1234
username: vikas pass: vikaspro
#21
