### ISSUE TITLE
Does not work + decrypted.

### ISSUE THREAD

**Issue by ghgiStudios** [samay825/Sms-Bomb#22]
This does not work at all and also this is very,very easy to decrypt and i already mostly have, somewhat werid looking due to compression but im able to see about 90% of the code so i recommend you change that or at this point just make it open source.

**Comment by ghgiStudios** [comment]
the API links dont work (main reason why its broke but i havent tested all methods/links)

**Comment by ghgiStudios** [comment]
Actually based on your other projects the same method could decrypt all of them in about 5 minutes (by hand)

**Comment by samay825** [comment]
as the basic this sms tool is for indian number brother  as soon as possible i will release global and like decrypt i will change the encrypt way of marshal and passwords with new method

**Comment by samay825** [comment]
contact me in instagram @sincryptzork
