### ISSUE TITLE
Only for India?

### ISSUE THREAD

**Issue by profesionalleet1337** [samay825/Sms-Bomb#29]
Could be made to work for Europe countrie's ? Not only for Indian phone's .. ?

**Comment by samay825** [comment]
Yes I can make for Europe also dm me in telegram
@sincryptzork

**Comment by profesionalleet1337** [comment]
> Yes I can make for Europe also dm me in telegram @sincryptzork

What's up bro ? When u plan to make this ?

**Comment by profesionalleet1337** [comment]
@samay825 any news?

**Comment by profesionalleet1337** [comment]
@samay825 hey bro, what's up ?

**Comment by profesionalleet1337** [comment]
@samay825 Hello my friend, did u updated ? Does it work for Europe now ?
