### ISSUE TITLE
IM HAVING PROBLEMS

### ISSUE THREAD

**Issue by Top5Grinch** [samay825/Sms-Bomb#30]
Ok im new with this hacking stuff but i done a couple things here & there using python or whatever i need to use. Im  confused on this tho, idk if i messed something up but idk its not working & i need help

I tried to send Sms to many numbers but they texts never go to the phone.

![Screenshot (18)](https://github.com/samay825/Sms-Bomb/assets/150621684/592b5df4-3cb9-4293-aa12-753bfab940f3)

**Comment by Top5Grinch** [comment]
list index out of range ? do i get a new list somewhere? if so where can i find that

**Comment by samay825** [comment]
I recommend to use in termux 
Try in termux and don't give spaces between numbers and works for Indian numbers ... 
If it goes with same error I will fix it within 1 day
