### ISSUE TITLE
Already installed alert 

### ISSUE THREAD

**Issue by Sivamkannan** [samay825/Sms-Bomb#33]
![Screenshot_2024-01-16-21-47-09-16_84d3000e3f4017145260f7618db1d683.jpg](https://github.com/samay825/Sms-Bomb/assets/154779946/2294d26b-a2ea-40ca-815f-216f79a07b5d)

**Comment by Sivamkannan** [comment]
Already installed in directory alert

**Comment by Sivamkannan** [comment]
Already exist in directory alert

**Comment by samay825** [comment]
You have already installed the script ... Just run the script brother
