### ISSUE TITLE
Error in custom SMS 

### ISSUE THREAD

**Issue by ermkmandawar** [samay825/Sms-Bomb#34]
Custom SMS not sent showing error in termux 
![Screenshot_2024-01-18-08-04-53-54_84d3000e3f4017145260f7618db1d683](https://github.com/samay825/Sms-Bomb/assets/60051557/5d6e2a29-3b73-4a38-9d0d-e4e5ba9b7edf)

**Comment by samay825** [comment]
Yeah sorry for inconvenience .. we are updating the script
