### ISSUE TITLE
how do i stop getting bombed

### ISSUE THREAD

**Issue by flamianblaze** [samay825/Sms-Bomb#4]
tried bombing my mom's phone but now it ain't stopping bruh add a stop bombing button or something please
or atleast add a bombing limit that we can set to a specific number or set to 0 for unlimited, please reply to this quick i need immediate assistance

**Comment by samay825** [comment]
brother updating soon ..

**Comment by samay825** [comment]
> tried bombing my mom's phone but now it ain't stopping bruh add a stop bombing button or something please or atleast add a bombing limit that we can set to a specific number or set to 0 for unlimited, please reply to this quick i need immediate assistance

**Comment by samay825** [comment]
update the script issue fixed .
