### ISSUE TITLE
Not executing, main.py on Linux

### ISSUE THREAD

**Issue by Abhijeetbyte** [samay825/Sms-Bomb#40]
![image](https://github.com/samay825/Sms-Bomb/assets/80936610/a3a4b243-8add-484c-8475-f0560b6fad12)

Python version

![image](https://github.com/samay825/Sms-Bomb/assets/80936610/7b440f72-ab57-4112-bb4f-a03c537392a6)

**Comment by samay825** [comment]
in linux python 3.9.2 supported  soon i will update for linux , Therefore you can use in termux

**Comment by Abhijeetbyte** [comment]
Ok, thanks for your response, let me try on python 3.9

**Comment by Abhijeetbyte** [comment]
![image](https://github.com/samay825/Sms-Bomb/assets/80936610/30adbcaa-6af3-44aa-a314-1ac7e0eff257)

![image](https://github.com/samay825/Sms-Bomb/assets/80936610/7c549730-b10e-456e-8dc5-18a34aa51886)

![image](https://github.com/samay825/Sms-Bomb/assets/80936610/edb8ed6e-7970-479a-ba7d-4b5a8f90b89d)

While execution got some module error ! Why  ?  ?

**Comment by Abhijeetbyte** [comment]
@samay825 

Would you like to say a thing? related to my prior queries on python 3.9
