### ISSUE TITLE
The b#omber will not Stop Bombing even after CTRL+V command HELP!!!! 

### ISSUE THREAD

**Issue by ShawnBmbr** [samay825/Sms-Bomb#46]
Description of the bug
The bug doesn't allow to stop the b#ombing.
No matter how many times you enter the number and try to stop it using CTRL+V.New or old number keeps getting SMS no matter what I do to close or end it .

Expected behavior
Stop the b#ombing on entered number

**Smartphone
-Smartphone - Poco F5 Android 14

OS: [Linux based]
Terminal [Termux for Android]
Python Version [Latest]
Additional context
Tried on my number for verification if it works and i have recieved 1500 SMS and the stop command (Ctrl+V) doesn't work. Also tried termux link provided .Please HELP!!!STOP IT!!

**Comment by filtroxx** [comment]
Same brother this shi.. isn't Stopping now what should i do

**Comment by samay825** [comment]
I will update this feature soon ...
