### ISSUE TITLE
broo need paid version as you had set the same number only once so need paid version 

### ISSUE THREAD

**Issue by foolish99** [samay825/Sms-Bomb#9]
https://t.me/coca_colaaas

my telegram id (need paid version and gonna be like same number i can bomb unlimited times)

![Screenshot_20220723_182524](https://user-images.githubusercontent.com/108453739/180606283-008f0b4f-6af4-4f1b-976e-a6eda83cbee3.jpg)

and and can u set the free version like unlimited times 
i mean the same number unlimited times

**Comment by samay825** [comment]
okay bro i will contact you in telegram but you can msg me in instagtam @sincryptzork

**Comment by foolish99** [comment]
already texted uu on instagram both of u guys 
vampier_ritik olso and sincryptzork too 
my insta id is subhrat_jain
![Uploading Screenshot_20220724_103723.jpg…]()
